### ISSUE TITLE
Json file-id

### ISSUE THREAD

**Issue by oliverluup** [oliverluup/projektip-ev5#3]
Dummy ülesanded mis on kohe kaasas programmiga
nt:
pealinnad
klahvikombinatsioonid
ajalugu
jne

**Comment by keijoraamat** [comment]
Jätaks vahest klahvi kombod välja kuna need on erinevates op süsteemides ja erinevate klaveri paigutustega erinevad. Läheb muidu ülekäte json faili struktuur.
